services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyDataSync\:
        resource: '../../{Service}'
        tags: ['controller.service_arguments']
