services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyDataSync\:
        resource: '../../{Command,Repository,Service}'
        exclude: '../../Service/PropertyLinkStore.php'
